"""Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

import os
from pathlib import Path

# Environment variables
APP_NAME = os.environ.get("DAB_SERVER_NAME", "")
BASE_DIR = Path(os.environ.get("DAB_SERVER_BASE_DIR", APP_NAME)) or Path.cwd().resolve()
POSTGRES_DATABASE = os.environ.get("DAB_POSTGRES_DATABASE", "")
POSTGRES_USERNAME = os.environ.get("DAB_POSTGRES_USERNAME", "")
POSTGRES_PASSWORD = os.environ.get("DAB_POSTGRES_PASSWORD", "")
POSTGRES_HOST = os.environ.get("DAB_POSTGRES_HOST", "localhost")
POSTGRES_PORT = int(os.environ.get("DAB_POSTGRES_PORT", "5432"))
POSTGRES_CONN_MAX_AGE = int(os.environ.get("DAB_POSTGRES_CONN_MAX_AGE", "600"))
POSTGRES_POOL_ENABLED = bool(os.environ.get("DAB_POSTGRES_POOL_ENABLED", "false"))
POSTGRES_POOL_MIN_SIZE = int(os.environ.get("DAB_POSTGRES_POOL_MIN_SIZE", "1"))
POSTGRES_POOL_MAX_SIZE = int(os.environ.get("DAB_POSTGRES_POOL_MAX_SIZE", "10"))
POSTGRES_COMMAND_TIMEOUT = int(os.environ.get("DAB_POSTGRES_COMMAND_TIMEOUT", "30"))


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-1vh@c=j9x6n+@#8lw4&n3g)3y(jd!_+1ra-e4+xn=-4941h(()"  # noqa: S105

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.environ.get("DAB_SERVER_DEBUG", "false"))

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_async_backend",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = f"{APP_NAME}.core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = f"{APP_NAME}.core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django_async_backend.db.backends.postgresql",
        "NAME": POSTGRES_DATABASE,
        "USER": POSTGRES_USERNAME,
        "PASSWORD": POSTGRES_PASSWORD,
        "HOST": POSTGRES_HOST,
        "PORT": POSTGRES_PORT,
        "CONN_MAX_AGE": POSTGRES_CONN_MAX_AGE,
        "OPTIONS": {
            "pool": {
                "min_size": POSTGRES_POOL_MIN_SIZE,
                "max_size": POSTGRES_POOL_MAX_SIZE,
                "command_timeout": POSTGRES_COMMAND_TIMEOUT,
            }
            if POSTGRES_POOL_ENABLED
            else {},
        },
    },
    "testing": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}
