# Generated by Django 6.1 on 2026-09-11 15:21

import django.db.models.deletion
import django_async_backend.db.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(editable=False, max_length=64, unique=True)),
                ('content', models.BinaryField()),
                ('size', models.PositiveBigIntegerField(editable=False)),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('size__gte', 0)), name='dab_blobs_blob_size_gte_0'), models.CheckConstraint(condition=models.Q(('reference_count__gte', 0)), name='dab_blobs_blob_refcount_gte_0')],
            },
            bases=(django_async_backend.db.models.base.AsyncModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BlobReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(editable=False)),
                ('field', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blob', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='references', to='dab_blobs.blob')),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='dab_blobs_blobref_object_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'field', 'blob'), name='dab_blobs_blobreference_uniq')],
            },
        ),
    ]
