# Generated by Django 6.1 on 2026-09-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DelayedRedelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=64)),
                ('tier', models.CharField(choices=[('urgent', 'URGENT'), ('high', 'HIGH'), ('default', 'DEFAULT'), ('low', 'LOW')], max_length=16)),
                ('attempt_no', models.PositiveSmallIntegerField()),
                ('state', models.CharField(choices=[('pending', 'pending'), ('sent', 'sent'), ('failed', 'failed')], db_index=True, default='pending', max_length=16)),
                ('message_body', models.JSONField()),
                ('message_headers', models.JSONField()),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'scheduled_at'], name='dab_redeliv_scan_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=64, unique=True)),
                ('task_name', models.CharField(db_index=True, max_length=255)),
                ('tier', models.CharField(choices=[('urgent', 'URGENT'), ('high', 'HIGH'), ('default', 'DEFAULT'), ('low', 'LOW')], default='default', max_length=16)),
                ('state', models.CharField(choices=[('enqueued', 'ENQUEUED'), ('running', 'RUNNING'), ('retrying', 'RETRYING'), ('success', 'SUCCESS'), ('failed', 'FAILED'), ('dead', 'DEAD')], db_index=True, default='enqueued', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=1)),
                ('last_error_type', models.CharField(blank=True, default='', max_length=255)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['updated_at'], name='dab_trace_updated_idx')],
            },
        ),
    ]
